global:
  scrape_interval:     10s
  evaluation_interval: 10s
scrape_configs:
  - job_name: 'vanus'
    static_configs:
      - targets:
          - 'host.docker.internal:2112' # controller
          - 'host.docker.internal:2113' # gateway
          - 'host.docker.internal:2114' # store
          - 'host.docker.internal:2115' # timer
          - 'host.docker.internal:2116' # trigger
