---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vanus-grafana
  name: vanus-grafana
  namespace: vanus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vanus-grafana
  template:
    metadata:
      labels:
        app: vanus-grafana
    spec:
      containers:
        - image: grafana/grafana
          imagePullPolicy: Always
          name: grafana
          ports:
            - containerPort: 3000
              name: grafana
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: vanus-grafana
  name: vanus-grafana
  namespace: vanus
spec:
  type: NodePort
  ports:
    - name: vanus-grafana
      nodePort: 30300
      port: 3000
      targetPort: 3000
  selector:
    app: vanus-grafana
