apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vanus-prometheus
  name: vanus-prometheus
  namespace: vanus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vanus-prometheus
  template:
    metadata:
      labels:
        app: vanus-prometheus
    spec:
      containers:
        - image: prom/prometheus
          imagePullPolicy: Always
          name: prometheus
          ports:
            - containerPort: 9090
              name: prometheus
          volumeMounts:
            - mountPath: /etc/prometheus
              name: config-prometheus
      volumes:
        - configMap:
            name: config-prometheus
          name: config-prometheus
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: vanus-prometheus
  name: vanus-prometheus
  namespace: vanus
spec:
  type: NodePort
  ports:
    - name: vanus-prometheus
      nodePort: 30390
      port: 9090
      targetPort: 9090
  selector:
    app: vanus-prometheus