apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vanus-prometheus
  name: vanus-prometheus
  namespace: vanus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vanus-prometheus
  template:
    metadata:
      labels:
        app: vanus-prometheus
    spec:
      containers:
        - image: prom/prometheus
          imagePullPolicy: Always
          name: prometheus
          args:
            - "--storage.tsdb.retention.time=12h"
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
          ports:
            - containerPort: 9090
              name: prometheus
          resources:
            requests:
              cpu: 500m
              memory: 500M
            limits:
              cpu: 1
              memory: 1Gi
          volumeMounts:
            - name: config-prometheus
              mountPath: /etc/prometheus
            - name: prometheus-storage-volume
              mountPath: /prometheus/
      volumes:
        - name: config-prometheus
          configMap:
            defaultMode: 420
            name: config-prometheus
        - name: prometheus-storage-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: vanus-prometheus
  name: vanus-prometheus
  namespace: vanus
spec:
  type: NodePort
  ports:
    - name: vanus-prometheus
      nodePort: 30390
      port: 9090
      targetPort: 9090
  selector:
    app: vanus-prometheus