# https://github.com/bibinwilson/kubernetes-prometheus/blob/master/config-map.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-prometheus
  namespace: vanus
data:
  prometheus.yml: |
    global:
      scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
      evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
    
    # Alertmanager configuration
    alerting:
      alertmanagers:
        - static_configs:
            - targets:
              # - alertmanager:9093

    # Here it's Prometheus itself.
    scrape_configs:
      # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
      - job_name: 'prometheus'    
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'vanus-controller'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_name]
          regex: (^vanus-controller-\d+)
          action: keep
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_vanus_dev_metrics_port]
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          target_label: __address__
        - source_labels: [__meta_kubernetes_namespace]
          regex: (^vanus$)
          action: keep
      - job_name: 'node-exporter'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
        - source_labels: [__meta_kubernetes_endpoints_name]
          regex: 'node-exporter'
          action: keep
        - source_labels: [__meta_kubernetes_namespace]
          regex: (^vanus$)
          action: keep